version: 1

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

release:
  disable: true

publishers:
  - name: google-cloud-artifact-registry
    env:
      - GOOGLE_APPLICATION_CREDENTIALS={{ quote (expandenv "$HOME/.config/gcloud/application_default_credentials.json") }}
    dir: "{{ dir .ArtifactPath}}"
    cmd: gcloud artifacts apt upload bonfire-apt --source={{ .ArtifactName}}


nfpms:
  - package_name: apt-test
    homepage: https://github.com/bonfirestudios/go-arcade/
    maintainer: Scott Chaney <scott@bonfirestudios.com>
    description: |-
            Test for apt pipeline
    formats:
      - deb
